### ISSUE TITLE
Switch to the new issue migration API

### ISSUE THREAD

**Issue by The-Compiler** [nicoddemus/bitbucket_issue_migration#1]
So this is the answer I got from GitHub support:

> Thanks for reaching out and sorry to hear you've been having trouble. 
> 
> Creating issues and comments via the API triggers email notifications just like they'd be triggered when you create content via the Web UI. The abuse rate limit was introduced in order to prevent spikes in notification emails which cause problems for users and our infrastructure.
> 
> Instead of using the regular issues API, you could use a new API endpoint we're working on and which was designed with such migrations in mind. It should cut down on the number of API requests you need to make and it'll also allow you to preserve the dates of issues and comments that you migrate. And the best thing is that this endpoint doesn't trigger notifications and isn't affected by the abuse rate limits. We wrote up a walkthrough of it in this gist (https://gist.github.com/jonmagic/5282384165e0f86ef105). Could you give that a try with a few issues and a test project, and see if it fits your needs?
> 
> Also, since the target repository (The-Compiler/pytest-unofficial) has 0 watchers, another option would be that we temporarily whitelist your account so that you can use the regular issues API and don't hit the abuse rate limit. The first approach would be preferred by us, but if that doesn't work for you for some reason -- let me know and I'll whitelist the account you're using for importing. Can you confirm that you're importing issues only into The-Compiler/pytest-unofficial?

I guess we could either do things at a slower pace, or request a whitelist for both the test and the final repo (and hope we can create the issues before there are a lot of watchers)... but the best thing would be to migrate the script to that new API.

Can you do that, @nicoddemus? I'm not very experienced with using web APIs, and that seems to be a bit a bigger task than I thought :smile:

**Comment by nicoddemus** [comment]
I will try to use the new import API then, it seems to be the better solution overall and a better contribution to the upstream repository.

I will have some time tomorrow to work on this I think, but if anybody else wants to tackle this before then be my guest! :smile:

**Comment by nicoddemus** [comment]
(Btw, nice that they answered support requests so quickly!)

**Comment by The-Compiler** [comment]
It's crazy, the answer was there 5 minutes or so after I sent it. :+1:

Some thoughts:

How are you planning to add this? I guess the original way of doing things should still work, i.e. it could be some commandline option, as the API is still beta.

Also, I guess [pygithub3](https://github.com/copitux/python-github3) won't have support for that API yet, so I see two ways to go forward:
- Add support to pygithub3 and contribute to that, convince them to do a release, and then update the script.
- Just add something based on [requests](http://python-requests.org) to the script.

Of course the first one would be the nicer to do, but I haven't looked at its code yet.

**Comment by nicoddemus** [comment]
Updated the script to use the Issue Import API, you can see the changes [here](https://github.com/nicoddemus/bitbucket_issue_migration/commit/ac123bcc36fc50eab130b322df426c32999b318a).

I decided to go with using `requests`, since adding support to `pygithub3` would be a lot more effort than I'm willing to spend at the moment. :sweat_smile: 

I have sent an email to the list to gather feedback about the [imported issues](https://github.com/nicoddemus/pytest-issues-migration/issues), feel free to comment in there as well. :smile:

**Comment by The-Compiler** [comment]
Yay! I can understand that, I'd probably have done the same - and I'm not even sure if the contribution would've been welcome, as it's still a WIP/beta API.

I guess when it's finished, we should post the link to the script as a comment to the gist so others don't have to reinvent the wheel.

More comments on the ML :smile:

Thanks for all your work! :+1:

**Comment by nicoddemus** [comment]
I plan to open a PR upstream when we're done, but if it doesn't get accepted then certainly posting a link on the gist might be the way to go.  :smile:
